name: TFLINT Module

on:
  pull_request:
    branches:
      - main

jobs:
  tflint:
    uses: dnogu/ActionCI/.github/workflows/tflint.yaml@main
    secrets: inherit
  docs:
    uses: dnogu/ActionCI/.github/workflows/tf-docs.yaml@main
    secrets: inherit
    needs: tflint

